<!--<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#">rien</a>
</nav>
<nav class="navbar navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">SolidServ</a>
</nav>-->
<header id="nav-desktop">
    <div class="clear"></div>
    <nav class="fixed-header">
        <div class="site-title visible-title"><a href="./"><img src="assets/LogoBrute.png"> SolidServ</a></div>
        <ul class="">
            <li><a href="">Home</a></li>
            <li><a href="">Contact</a></li>
        </ul>
    </nav>
</header>